USE FederationOfAthletics

CREATE TABLE CoachComitee
(
	CCID INT PRIMARY KEY,
	NAME VARCHAR(50),
	BUDGET INT NOT NULL
)

CREATE TABLE Coach
(
	CID INT PRIMARY KEY,
	NAME VARCHAR(50),
	AGE INT,
	SPECIALIZATION VARCHAR(50),
	CCID INT not null,
	CONSTRAINT FK_COACH_CCID FOREIGN KEY(CCID) REFERENCES CoachComitee(CCID)
)

CREATE TABLE SportingClub
(
	SCID INT PRIMARY KEY,
	NAME VARCHAR(50),
	BUDGET INT NOT NULL
)

CREATE TABLE Competition
(
	COMID INT PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	TYPE VARCHAR(50),
	BUDGET INT NOT NULL
)

CREATE TABLE STADIUM
(
	SID INT PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	CAPACITTY INT NOT NULL
)

CREATE TABLE Cantonment
(
	CANID INT PRIMARY KEY,
	DESCRIPTION VARCHAR(150),
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL
)

CREATE TABLE NationalTeam
(
	NTID INT PRIMARY KEY,
	COUNTRY_NAME VARCHAR(50) NOT NULL,
	NO_OF_ATHLETES INT NOT NULL,
)

CREATE TABLE Athlete
(
	AID INT PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	AGE INT NOT NULL,
	SPECIALIZATION VARCHAR(50),
	CID INT not null,
	SCID INT not null,
	NTID INT not null,
	CONSTRAINT FK_Athlete_CID FOREIGN KEY(CID) REFERENCES Coach(CID),
	CONSTRAINT FK_Athlete_SCID FOREIGN KEY(SCID) REFERENCES SportingClub(SCID),
	CONSTRAINT FK_Athlete_NTID FOREIGN KEY(NTID) REFERENCES NationalTeam(NTID)
)

CREATE TABLE Training
(
	AID INT not null,
	SID INT not null,
	CANID INT not null,
	NAME VARCHAR(50) NOT NULL,
	NO_OF_REP INT,
	CONSTRAINT FK_Training_AID FOREIGN KEY(AID) REFERENCES Athlete(AID),
	CONSTRAINT FK_Training_SID FOREIGN KEY(SID) REFERENCES Stadium(SID),
	CONSTRAINT FK_Training_CANID FOREIGN KEY(CANID) REFERENCES Cantonment(CANID),

	PRIMARY KEY(AID,SID,CANID)
)

CREATE TABLE Performs_in
(
	AID INT not null,
	COMID INT not null,

	CONSTRAINT FK_Performs_AID FOREIGN KEY(AID) REFERENCES Athlete(AID),
	CONSTRAINT FK_Performs_COMID FOREIGN KEY(COMID) REFERENCES Competition(COMID),


	PRIMARY KEY(AID,COMID)
)

CREATE TABLE Employee
(
	EID INT not null,
	SCID INT,
	SPECIALIZATION INT
)

CREATE TABLE Versions
(
	VID INT not null,
	PRIMARY KEY(VID)
)


select *
from Coach
select *
from CoachComitee

delete
from Coach
where AGE in (25,26,27,28,29,30,21)